#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

# Alpine 2.x is defunct - the upstream package repos are no longer there - gets 404

---
name: Alpine

on:
  workflow_call:
    inputs:
      version:
        description: The Alpine version docker tag
        type: string
        required: true
      debug:
        type: string
        default: ''
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: alpine:${{ inputs.version }}
    permissions:
      contents: read
    env:
      DEBUG: ${{ inputs.debug }}
    steps:
      - name: Environment
        run: env | sort

      - name: Install Git & Make
        # apk add --no-cache switch isn't available until Alpine 3
        #run: apk add --no-cache git make
        run: apk update && apk add git make

      - name: Git version
        run: git --version

      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - name: Init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi

      - name: Build
        run: |
          if grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi

      - name: Test
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
