#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Alpine

#env:
#  DEBUG: 1

on:
  workflow_call:
    inputs:
      debug:
        type: string
        default: ''
        required: false

jobs:
  build:
    name: Build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: alpine:latest
    env:
      DEBUG: ${{ inputs.debug }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install git & make
        run: apk add --no-cache git make
      - name: init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi
      - name: build
        run: |
          if grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi
      - name: test
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
