#
#  Author: Hari Sekhon
#  Date: 2022-05-12 16:37:55 +0100 (Thu, 12 May 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# https://github.com/datreeio/action-datree

# Logs results to https://datree.io

---
name: Datree

on:
  workflow_call:
    inputs:
      path:
        type: string
        default: '**/*.yaml'
        required: false
      # https://hub.datree.io/setup/cli-arguments
      args:
        type: string
        default: --only-k8s-files
        required: false
      isHelmChart:
        type: boolean
        required: false
      helmArguments:
        # eg. '--values values.yaml'
        type: string
        required: false
      isKustomization:
        type: boolean
        required: false
      kustomizeArguments:
        type: string
        required: false
    secrets:
      DATREE_TOKEN:
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment
        run: env | sort

      - name: Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: ${{ inputs.path }}
          cliArguments: ${{ inputs.args }}
          isHelmChart: ${{ inputs.isHelmChart }}
          helmArguments: ${{ inputs.helmArguments }}
          isKustomization: ${{ inputs.isKustomization }}
          kustomizeArguments: ${{ inputs.kustomizeArguments }}
