#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Fork Update

on:
  workflow_call:
    secrets:
      PAT_FORK_UPDATE:
        description: PAT token with permissions to create Pull Requests (forked repo tokens are read only)
        required: true
    inputs:
      branches-to-pr:
        type: string
        required: false
        default: |
          master
          main
          develop
          dev
          staging
          production
      branches-to-automerge:
        type: string
        required: false
        default: |
          master
          main
          develop
          dev
          staging
      debug:
        type: string
        required: false
        #default: '1'
  workflow_dispatch:
    inputs:
      debug:
        type: string
        required: false
        #default: '1'
  schedule:
    - cron: '0 10 * * 2'

env:
  # XXX: default GitHub Actions token is neutered to read-only in forks - must use a Personal Access Token (PAT) with repo:write and org:read permissions assigned to it
  GITHUB_TOKEN: ${{ secrets.PAT_FORK_UPDATE || github.token }}
  BRANCHES_TO_PR: ${{ inputs.branches-to-pr || github.event.inputs.branches-to-pr }}
  BRANCHES_TO_AUTOMERGE: ${{ inputs.branches-to-automerge || github.event.inputs.branches-to-automerge }}
  GH_NO_UPDATE_NOTIFIER: 1
  DEBUG: ${{ inputs.debug || github.event.inputs.debug }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false  # killing this part way through may leave PRs without auto-merging

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  create_pr:
    name: Create Fork Update PRs
    if: github.ref_type == 'branch' && ( github.ref_name == 'master' || github.ref_name == 'main' )
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    container: harisekhon/bash-tools
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v2

      - name: GH CLI auth status
        run: |
          gh config set prompt disabled
          GITHUB_TOKEN="${{ github.token }}" gh auth status
          #gh auth login  # errors out if GITHUB_TOKEN is set
          gh auth status
          #gh api /user | jq  # implicit pipe collapses format, force through jq to avoid this

      # default actions token is pretty useless in forks
      #
      # gh: Resource not accessible by integration (HTTP 403)
      # {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/users#get-the-authenticated-user"}
      #- name: GH API User
      #  run: gh api /user

      - name: Generate environment variable IS_FORK
        run: |
          IS_FORK="$(gh api /repos/{owner}/{repo} -q .fork)"
          echo "IS_FORK=$IS_FORK" >> "$GITHUB_ENV"

      - name: Create PRs & Automerge
        if: ${{ env.IS_FORK == 'true' }}
        run: |
          github_repo_fork_update.sh
