#
#  Author: Hari Sekhon
#  Date: 2022-02-01 13:56:31 +0000 (Tue, 01 Feb 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

# https://github.com/Checkmarx/kics/blob/master/docs/integrations_ghactions.md

---
name: Kics

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: .
      # https://github.com/Checkmarx/kics/blob/master/docs/configuration-file.md
      config:
        type: string
        required: false
      queries:
        type: string
        required: false
      fail_on:
        type: string
        required: false
        #default: high,medium
      ignore_on:
        type: string
        required: false
        default: results
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  kics:
    name: Kics Scan
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      CONFIG: ${{ inputs.config }}
      CONFIG_FILE: ''
    steps:
      - uses: actions/checkout@v2

      - name: Make results-dir
        run: mkdir -pv results-dir

      - name: Create Config file
        if: ${{ env.CONFIG }}
        run: |
          cat <<EOF >>kics.config
          ${{ env.CONFIG }}
          EOF
          echo "CONFIG_FILE=kics.config" >> "$GITHUB_ENV"

      # https://github.com/Checkmarx/kics-github-action
      - name: Kics Scan
        uses: checkmarx/kics-action@master
        with:
          path: ${{ inputs.path }}
          fail_on: ${{ inputs.fail_on }}
          ignore_on_exit: ${{ inputs.ignore_on_exit }}
          output_path: results-dir
          output_formats: 'json,sarif'
          #config_path: ${{ env.CONFIG_FILE }}
          queries: ${{ inputs.queries }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results-dir/results.sarif

      - name: Display Results
        run: jq . < results-dir/results.json
