#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Make

on:
  workflow_call:
    inputs:
      container:
        description: The docker image:version container to build inside
        type: string
        default: null
        required: false
      build-target:
        description: The Make build target
        type: string
        required: false
        default: ''
      no-test:
        description: Don't run 'make test' after build
        type: boolean
        required: false
        default: false
      caches:
        description: Caches eg. pip, cpan, maven, sbt, gradle etc...
        type: string
        required: false
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    # not bash because we could be passed an Alpine container
    shell: sh -eux {0}

env:
  BUILD_TARGET: ${{ inputs.build-target || github.event.inputs.build-target }}
  DEBIAN_FRONTEND: noninteractive
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  make:
    name: Make
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Environment
        run: env | sort

      - name: Install Bash, Git & Make
        run: |
          sudo=sudo
          if [ "${EUID:-${UID:-$(id -u)}}" = 0 ]; then
            sudo=''
          fi
          if command -v apk; then
            # apk add --no-cache isn't available until Alpine 3
            #$sudo apk add --no-cache git make
            $sudo apk update && apk add bash git make
          elif command -v apt-get; then
            if grep -Fxq 'ID=debian' /etc/*release &&
               grep -xq 'VERSION_ID="[67]"' /etc/*release; then
              # switch APT sources to archive.debian.org
              $sudo sed -i 's/deb.debian.org/archive.debian.org/' /etc/apt/sources.list
              $sudo sed -i 's/security.debian.org/archive.debian.org/' /etc/apt/sources.list
            fi
            $sudo apt-get update
            $sudo apt-get install -y -q bash git make
          #elif command -v dnf; then
          #  $sudo dnf install -y -q bash git make
          elif command -v yum; then
            # CentOS is EOL - but for some reason CentOS 7 works without this, while CentOS 6 and 8 need archive
            if grep -qi centos /etc/*release && grep -q '^VERSION="[68]"$' /etc/*release; then
              $sudo sed -i 's/^[[:space:]]*mirrorlist/#mirrorlist/' /etc/yum.repos.d/CentOS-*
              $sudo sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|' /etc/yum.repos.d/CentOS-*
            fi
            $sudo yum install -y -q bash git make
          fi

      - name: Git version
        run: git --version

      - name: Git Checkout
        # git version too old to support recursive submodules checkout on older version Debian and Ubuntu <= 18
        #uses: actions/checkout@v2
        #with:
        #  submodules: recursive  # requires Git 2.18+ to be installed first
        run: git clone "https://${{github.token}}@github.com/$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE"

      - name: Maven Cache
        if: contains(inputs.caches, 'maven')
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ runner.arch }}-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-maven-cache-

      - name: Maven Wrapper
        if: contains(inputs.caches, 'maven')
        uses: actions/cache@v1
        with:
          path: ~/.m2/wrapper
          key: ${{ runner.os }}-${{ runner.arch }}-maven-wrapper-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-maven-wrapper-

      - name: Gradle Cache
        if: contains(inputs.caches, 'gradle')
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ runner.arch }}-gradle-cache-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-gradle-cache-

      - name: Gradle Wrapper
        if: contains(inputs.caches, 'gradle')
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ runner.arch }}-gradle-wrapper-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-gradle-wrapper-

      - name: SBT Cache
        if: contains(inputs.caches, 'sbt')
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-${{ runner.arch }}-sbt-cache-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-sbt-cache

      - name: SBT Ivy Cache
        if: contains(inputs.caches, 'sbt')
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-${{ runner.arch }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-sbt-ivy-cache-

      - name: Init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi

      - name: Build
        run: |
          if [ -n "${BUILD_TARGET:-}" ] &&
             grep -q "^$BUILD_TARGET:" Makefile; then
             make "$BUILD_TARGET"
          elif grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi

      - name: Test
        if: inputs.no-test != true && github.event.inputs.no-test != true
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
