#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Make

on:
  workflow_call:
    inputs:
      runs-on:
        description: The base OS to run on. Must be ubuntu if specifying container
        type: string
        default: ubuntu-latest
        required: true
      container:
        description: The docker image:version container to build inside
        type: string
        default: null
        required: false
      build-target:
        description: The Make build target
        type: string
        required: false
        default: ''
      no-test:
        description: Don't run 'make test' after build
        type: boolean
        required: false
        default: false
      caches:
        description: Caches eg. pip, cpan, maven, sbt, gradle etc...
        type: string
        required: false
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    # not bash because we could be passed an Alpine container
    shell: sh -eux {0}

env:
  BUILD_TARGET: ${{ inputs.build-target || github.event.inputs.build-target }}
  DEBIAN_FRONTEND: noninteractive
  DEBUG: ${{ inputs.debug || github.event.inputs.debug || '' }}

jobs:
  make:
    name: Make
    runs-on: ${{ inputs.runs-on }}
    container: ${{ inputs.container }}
    steps:
      - name: Environment
        run: env | sort

      - name: Install Bash, Git & Make
        run: |
          sudo=sudo
          if [ "${EUID:-${UID:-$(id -u)}}" = 0 ]; then
            sudo=''
          fi
          if command -v apk; then
            # apk add --no-cache isn't available until Alpine 3
            #$sudo apk add --no-cache git make
            $sudo apk update && apk add bash git make
          elif command -v apt-get; then
            if grep -Fxq 'ID=debian' /etc/*release &&
               grep -xq 'VERSION_ID="[67]"' /etc/*release; then
              # switch APT sources to archive.debian.org
              $sudo sed -i 's/deb.debian.org/archive.debian.org/' /etc/apt/sources.list
              $sudo sed -i 's/security.debian.org/archive.debian.org/' /etc/apt/sources.list
            fi
            $sudo apt-get update
            $sudo apt-get install -y -q bash git make
          #elif command -v dnf; then
          #  $sudo dnf install -y -q bash git make
          elif command -v yum; then
            # CentOS is EOL - but for some reason CentOS 7 works without this, while CentOS 6 and 8 need archive
            if grep -qi 'NAME=.*CentOS' /etc/*release && grep -q '^VERSION="[68]"$' /etc/*release; then
              $sudo sed -i 's/^[[:space:]]*mirrorlist/#mirrorlist/' /etc/yum.repos.d/CentOS-*
              $sudo sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|' /etc/yum.repos.d/CentOS-*
            fi
            $sudo yum install -y -q bash git make
          fi

      - name: Brew Update
        if: startsWith(runner.os, 'macOS')
        run: which brew && brew update || echo

      - name: Git version
        run: git --version

      - name: Git Checkout
        # git version too old to support recursive submodules checkout on older version Debian and Ubuntu <= 18
        #uses: actions/checkout@v2
        #with:
        #  submodules: recursive  # requires Git 2.18+ to be installed first
        run: git clone "https://${{github.token}}@github.com/$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE"

      # ============================================================================ #
      # Python Caches
      #
      - name: Python Pip Cache Linux
        if: ( contains(inputs.caches, 'pip') || contains(inputs.caches, 'python') ) && startsWith(runner.os, 'Linux')
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ runner.arch }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-pip-

      - name: Python Pip Cache Mac
        if: ( contains(inputs.caches, 'pip') || contains(inputs.caches, 'python') ) && startsWith(runner.os, 'macOS')
        uses: actions/cache@v1
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-${{ runner.arch }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-pip-

      # ============================================================================ #
      # Perl Caches
      #
      - name: Perl CPAN Cache
        if: contains(inputs.caches, 'perl') || contains(inputs.caches, 'cpan')
        uses: actions/cache@v1
        with:
          path: ~/.cpan
          key: ${{ runner.os }}-${{ runner.arch }}-cpan-${{ hashFiles('**/cpan-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-cpan-

      - name: Perl CPANM Cache
        if: contains(inputs.caches, 'perl') || contains(inputs.caches, 'cpan') || contains(inputs.caches, 'cpanm')
        uses: actions/cache@v1
        with:
          path: ~/.cpanm
          key: ${{ runner.os }}-${{ runner.arch }}-cpanm-${{ hashFiles('**/cpan-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-cpanm-

      # ============================================================================ #
      # Ruby Gem Cache

      - name: Ruby Gem Cache
        if: contains(inputs.caches, 'ruby') || contains(inputs.caches, 'gem')
        uses: actions/cache@v1
        with:
          path: ~/.gem
          key: ${{ runner.os }}-${{ runner.arch }}-gem-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-ge,-

      # ============================================================================ #
      # Go Cache

      - name: Golang Pkg Cache
        if: contains(inputs.caches, 'golang')
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-

      # ============================================================================ #
      # Java Caches

      - name: Maven Cache
        if: contains(inputs.caches, 'maven')
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ runner.arch }}-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-maven-cache-

      - name: Maven Wrapper
        if: contains(inputs.caches, 'maven')
        uses: actions/cache@v1
        with:
          path: ~/.m2/wrapper
          key: ${{ runner.os }}-${{ runner.arch }}-maven-wrapper-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-maven-wrapper-

      # ============================================================================ #
      - name: Gradle Cache
        if: contains(inputs.caches, 'gradle')
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ runner.arch }}-gradle-cache-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-gradle-cache-

      - name: Gradle Wrapper
        if: contains(inputs.caches, 'gradle')
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ runner.arch }}-gradle-wrapper-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-gradle-wrapper-

      # ============================================================================ #
      - name: SBT Cache
        if: contains(inputs.caches, 'sbt')
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-${{ runner.arch }}-sbt-cache-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-sbt-cache

      - name: SBT Ivy Cache
        if: contains(inputs.caches, 'sbt')
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-${{ runner.arch }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-sbt-ivy-cache-

      # ============================================================================ #
      - name: Groovy Cache
        if: contains(inputs.caches, 'groovy')
        uses: actions/cache@v1
        with:
          path: ~/.groovy
          key: ${{ runner.os }}-${{ runner.arch }}-groovy-cache #-${{ hashFiles('**/*.groovy') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-groovy-cache

      # ============================================================================

      - name: Init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi

      - name: Build
        run: |
          if [ -n "${BUILD_TARGET:-}" ] &&
             grep -q "^$BUILD_TARGET:" Makefile; then
             make $BUILD_TARGET  # intentionally not quoting to pass multiple targets
          elif grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi

      - name: Test
        if: inputs.no-test != true && github.event.inputs.no-test != true
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
