#
#  Author: Hari Sekhon
#  Date: 2021-11-30 18:44:49 +0000 (Tue, 30 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Pluto

on:
  workflow_call

jobs:
  pluto:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Environment
        run: env | sort

      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master

      - name: Pluto detect-files
        run: |
          pluto detect-files -d .
