#
#  Author: Hari Sekhon
#  Date: 2022-03-11 17:51:59 +0000 (Fri, 11 Mar 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                    Terraform Plan PR and Apply master/main
# ============================================================================ #

---
name: Terraform

on:
  # call from a workflow with triggers like this
  #push:
  #  branches:
  #    - master
  #    - main
  #  paths:
  #    - '**/*.tf'
  #    - '**/*.tfvars'
  #    - '**/.terraform.lock.hcl'
  #    - .github/workflows/terraform.yaml
  #    #- !'**/*.md'
  #pull_request:
  #  branches:
  #    - master
  #    - main
  #  paths:
  #    - '**/*.tf'
  #    - '**/*.tfvars'
  #    - '**/.terraform.lock.hcl'
  #    - .github/workflows/terraform.yaml
  #    #- !'**/*.md'
  workflow_call:
    inputs:
      terraform-version:
        description: Terraform version to use. Will try to infer from .envrc if not given
        type: string
        required: false
      dir:
        description: Terraform base directory to execute in
        type: string
        default: ''
        required: false
      enforce-fmt-check:
        description: Enforce a format check on PRs - fail and do not show a plan if people don't format their code properly
        type: boolean
        default: true
        required: false
      debug:
        type: string
        required: false
        default: false
    secrets:
      # only if using Terraform Cloud backend
      TF_API_TOKEN:
        required: false
      # if managing AWS services or using an S3 backend
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_DEFAULT_REGION:
        required: false
      # if managing GCP services or using a GCS backend
      # either supply a GCP service account credential key
      GCP_SERVICEACCOUNT_KEY:
        required: false
      # OR workload identity provider and service_account, see:
      #
      #   https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: false
      GCP_SERVICE_ACCOUNT:
        required: false
      # GITHUB_TOKEN - because actions don't allow you to set GITHUB_TOKEN secret
      #              - this has to be a PAT (personal access token) if you are going to manage various repos and other aspects of GitHub via Terraform
      #              - token must have full repo permission to update the Pull Request with the Terraform Plan output
      GH_TOKEN:
        required: false

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ inputs.dir }}
  cancel-in-progress: false  # don't interrupt Terraform runs, you may end up with stale locks

defaults:
  run:
    shell: bash -euxo pipefail {0}
    # cannot use contexts or expressions under defaults.run
    #
    #   https://github.com/github-community/community/discussions/17981
    #
    #working-directory: ${{ inputs.dir }}

env:
  TF_IN_AUTOMATION: 1
  WORKDIR: ${{ inputs.dir }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  DEBUG: ${{ inputs.debug == 'true' || github.event.inputs.debug == 'true' || '' }}

jobs:
  # XXX: workaround for GitHub Actions not supporting secrets in step conditionals:
  #
  #   https://github.com/github-community/community/discussions/17983
  #
  #   https://github.com/actions/runner/issues/520
  #
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      aws: ${{ steps.aws.outputs.aws }}
      gcp_key: ${{ steps.gcp.outputs.gcp_key }}
      gcp_keyless: ${{ steps.gcp.outputs.gcp_keyless }}
      # secret is passed straight to setup terraform step so don't need to determine an extra step using this
      #terraform-cloud: ${{ steps.terraform-cloud.outputs.terraform-cloud }}
      terraform-version: ${{ steps.terraform-version.outputs.terraform-version }}
    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Terraform Version output
        id: terraform-version
        run: |
          if [ -n "${WORKDIR:-}" ]; then
            cd "$WORKDIR"
          fi
          if [ -f .envrc ]; then
            source .envrc
          fi
          if [ -n "${{ inputs.terraform-version }}" ]; then
            TERRAFORM_VERSION="${{ inputs.terraform-version }}"
          fi
          if [ -n "${TERRAFORM_VERSION:-}" ]; then
            echo "::set-output name=terraform-version::$TERRAFORM_VERSION"
          fi

      - name: Generate AWS output
        id: aws
        run: |
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ] &&
             [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ] &&
             [ -n "${{ secrets.AWS_DEFAULT_REGION }}" ]; then

            echo "AWS access key, secret key, and region are set"
            echo "::set-output name=aws::true"
          fi

      - name: Generate GCP output
        id: gcp
        run: |
          if [ -n "${{ secrets.GCP_SERVICEACCOUNT_KEY }}" ]; then

            echo "GCP service account key is set"
            echo "::set-output name=gcp_key::true"
          fi

          if [ -n "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}" ] &&
             [ -n "${{ secrets.GCP_SERVICE_ACCOUNT }}" ]; then

            echo "GCP keyless authentication identity provider and service account are set"
            echo "::set-output name=gcp_keyless::true"
          fi

      - name: GitHub
        id: github
        run: |
          if [ -n "${{ secrets.GH_TOKEN }}" ]; then
            echo "GitHub GH_TOKEN is set"
          fi

          # who are we logged in as (important both for PR comments and if managing GitHub via Terraform)
          gh auth status


  fmt_check:
    name: Fmt Check
    needs: setup
    if: inputs.enforce-fmt-check == true && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ needs.setup.outputs.terraform-version }}
          # for Terraform Cloud
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Version
        run: terraform version

      # force people creating pull requests to format it correctly or fail and don't show them a plan
      - name: Terraform Format Check
        id: fmt
        run: |
          if [ -n "${WORKDIR:-}" ]; then
            cd "$WORKDIR"
          fi
          terraform fmt -check


  terraform:
    name: Terraform
    needs:
      - setup
      - fmt_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: configure-aws-credentials
        if: needs.setup.outputs.aws == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # adapted from my Jenkins Shared Library - https://github.com/HariSekhon/Jenkins/blob/master/vars/gcpActivateServiceAccount.groovy
      - name: Google Cloud Activate ServiceAccount Key
        id: google-cloud-activate-serviceaccount
        if: needs.setup.outputs.gcp_key == 'true'
        run: |
          base64 --decode <<< "${{ secrets.GCP_SERVICEACCOUNT_KEY }}" > credentials.json
          gcloud auth activate-service-account --key-file=credentials.json
          rm -f credentials.json
          gcloud auth list

      # New GCP keyless authentication:
      #
      #   https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
      #
      - name: Google Cloud Keyless Auth
        id: google-cloud-auth
        if: needs.setup.outputs.gcp_keyless == 'true'
        uses: google-github-actions/auth@v0.4.0
        with:
          #workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          #service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.secrets.GCP_SERVICE_ACCOUNT }}

      # https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          # for Terraform Cloud
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        id: init
        run: |
          if [ -n "${WORKDIR:-}" ]; then
            cd "$WORKDIR"
          fi
          terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: |
          if [ -n "${WORKDIR:-}" ]; then
            cd "$WORKDIR"
          fi
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          if [ -n "${WORKDIR:-}" ]; then
            cd "$WORKDIR"
          fi
          # prefer it be explicitly set in the provider.tf
          # allow to pick up important environment variables such as GITHUB_ORGANIZATION from envrc
          #if [ -f .envrc ]; then
          #  source .envrc
          #fi
          terraform plan -input=false -no-color
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: |
            terraform
            ${{ steps.plan.outputs.stderr }}
            ${{ steps.plan.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style \`${{ needs.fmt_check.steps.fmt.outcome }}\`
            #### Terraform Initialization \`${{ steps.init.outcome }}\`
            #### Terraform Validation \`${{ steps.validate.outcome }}\`
            #### Terraform Plan \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Failed
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.event_name == 'push' && ( github.ref_name == github.event.repository.default_branch ) # || github.ref_name == 'main' || github.ref_name == 'master' )
        run: |
          if [ -n "${WORKDIR:-}" ]; then
            cd "$WORKDIR"
          fi
          #if [ -f .envrc ]; then
          #  source .envrc
          #fi
          terraform apply -input=false -auto-approve
