#
#  Author: Hari Sekhon
#  Date: 2022-02-11 15:50:21 +0000 (Fri, 11 Feb 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Terraform Validate

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    container: hashicorp/terraform:latest
    permissions:
      contents: read
    steps:
      - name: Environment
        run: env | sort

      - name: Git version
        run: git --version

      - uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

      - name: Terraform Validate
        run: terraform validate
