#
#  Author: Hari Sekhon
#  Date: 2022-01-31 16:49:05 +0000 (Mon, 31 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Trivy Docker Image Scan

on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/trivy.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - .github/workflows/trivy.yaml
  workflow_call:
    inputs:
      target:
        description: The docker image:tag for Trivy to analyze
        type: string
        required: true
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
  workflow_dispatch:
    inputs:
      target:
        description: The docker image:tag for Trivy to analyze
        type: string
        required: true
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  trivy:
    name: Trivy Docker Image Scan
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: aquasec/trivy:latest
    permissions:
      contents: read
    env:
      # ${{ inputs.* }}               is set by workflow_call
      # ${{ github.events.inputs.* }} is set by workflow_dispatch
      TARGET: ${{ inputs.target || github.event.inputs.target || 'harisekhon/bash-tools' }}
    steps:
      - uses: actions/checkout@v2

      - name: Environment
        run: env | sort

      - name: Trivy (Full Informational)
        run: |
          # informational to see all issues
          trivy image --no-progress "$TARGET"

      - name: Trivy (with Severity Error Out)
        if: ${{ inputs.severity || github.event.inputs.severity }}
        env:
          SEVERITY: ${{ inputs.severity || github.event.inputs.severity }}
        run: |
          # fail the pipeline if any of the issues are in $SEVERITY eg. HIGH,CRITICAL
          trivy image --no-progress --exit-code 1 --severity "$SEVERITY" "$TARGET"
