#
#  Author: Hari Sekhon
#  Date: 2022-01-31 16:49:05 +0000 (Mon, 31 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# https://github.com/aquasecurity/trivy-action

---
name: Trivy Config GitHub Security Alerts

on:
  workflow_call:
    inputs:
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
      debug:
        type: string
        default: true
  workflow_dispatch:
    inputs:
      severity:
        description: Set a severity to trigger CI workflow failure
        type: string
        default: HIGH,CRITICAL
        required: false
      debug:
        type: boolean
        required: false
        default: false

permissions:
  actions: read
  contents: read
  security-events: write

defaults:
  run:
    shell: sh -eux {0}

env:
  DEBUG: ${{ inputs.debug == true || github.event.inputs.debug == 'true' || '' }}

jobs:
  trivy:
    name: Trivy GitHub Security Alerts
    runs-on: ubuntu-latest
    #container: aquasec/trivy:latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner to generate sarif
        #if: ${{ ! ( inputs.no_sarif || github.event.inputs.sarif ) }}
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          hide-progress: false
          #format: template
          #template: '@/contrib/sarif.tpl'
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy sarif scan results to GitHub Security tab
        #if: ${{ ! ( inputs.no_sarif || github.event.inputs.sarif ) }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
