#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Validation

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
    inputs:
      # doesn't evaluate in time for container
      #docker_image_tag:
      #  type: string
      #  required: true
      #  default: latest
      # workflow calls only permit string/boolean/number - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
      debug:
        type: string
        default: ''
        required: false
      env:
        type: string  # pass in string in export shell format eg. export MYVAR=myvalue MYVAR2=myvalue2
        required: false
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  validate:
    name: Validate
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # evaluates to blank and fails to pull
    #container: harisekhon/pytools:${{ inputs.docker_image_tag }}
    #container: harisekhon/pytools:debian
    container: harisekhon/bash-tools:latest
    env:
      DEBUG: ${{ inputs.debug }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first
      - name: Setup environment variables
        run: |
          echo "${{ inputs.env }}" >> $GITHUB_ENV
          if [ -f tests/excluded.sh ]; then
            echo "BASH_EXCLUDED_FILES_FUNCTION=tests/excluded.sh" >> $GITHUB_ENV
          fi
      - name: Environment
        run: env | sort
      - name: Validate
        run: |
          check_all.sh
