#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

name: Validation

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 1'

jobs:
  validate:
    name: Validate
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: harisekhon/pytools
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Validate
        #env:
        #  DEBUG: 1
        run: |
          check_all.sh
