#
#  Author: Hari Sekhon
#  Date: Sat Jan 15 09:35:18 2022 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Validation

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_call:
    inputs:
      # doesn't evaluate in time for container
      #docker_image_tag:
      #  type: string
      #  required: true
      #  default: latest
      # workflow calls only permit string/boolean/number - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
      debug:
        type: string
        default: ''
        required: false
      env:
        type: string  # pass in string in export shell format eg. export MYVAR=myvalue MYVAR2=myvalue2
        default: ''
        required: false
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  validate:
    name: Validate
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # PyTools contains some extra tools, eg. use validate_yaml.py if check_yaml.sh yamllint dependencies aren't available
    # inputs evaluates to blank and fails to pull - not available at this stage
    #container: harisekhon/pytools:${{ inputs.docker_image_tag }}
    #container: harisekhon/pytools:debian
    container: harisekhon/pytools:centos
    #container: harisekhon/bash-tools:latest
    permissions:
      contents: read
    env:
      DEBUG: ${{ inputs.debug }}
      INPUTS: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first
      - name: Setup environment variables
        run: |
          echo "${{ env.INPUTS }}" >> "$GITHUB_ENV"
      - name: Environment
        run: env | sort
      - name: Validate
        run: |
          check_all.sh
